/*
    날짜 : 2025/07/14
    이름 : 이준우
    내용 : 2장 SQL 기본
*/

// select ' Hello Oracle !' from dual;

-- 실습 1-2. NUMBER 자료형 이해
CREATE TABLE TYPE_TEST_NUMBER (    
    num1 NUMBER,
    num2 NUMBER(2),
    num3 NUMBER(3, 1),
    num4 NUMBER(4, 2),
    num5 NUMBER(5, 6),
    num6 NUMBER(6, -1)
);

// 테이블 데이터 삭제
// delete from type_test_number;

insert into type_test_number (num1) values (1);
insert into type_test_number (num1) values (123);
insert into TYPE_TEST_NUMBER (num1) values (123.74);
insert into TYPE_TEST_NUMBER (num1) values (123.12345);

 //num2 NUMBER(2)
 insert into TYPE_TEST_NUMBER (num2) values (12);
 insert into TYPE_TEST_NUMBER (num2) values (123);
 insert into TYPE_TEST_NUMBER (num2) values (1.2);
 insert into TYPE_TEST_NUMBER (num2) values (1.23);
 insert into TYPE_TEST_NUMBER (num2) values (12.34567);
 insert into TYPE_TEST_NUMBER (num2) values (12.56789);
 insert into TYPE_TEST_NUMBER (num2) values (123.56789);


// 실습하기 1-3. 문자형 자료형 이해
insert into TYPE_TEST_NUMBER (num5) values (0.01);


// 실습하기 1-4. 테이블 생성
CREATE TABLE USER1 (
    USER_ID VARCHAR2(20),
    NAME VARCHAR2(20),
    HP CHAR(13),
    AGE NUMBER
);

// DROP TABLE USER1;

// 실습하기 1-5
INSERT INTO USER1 VALUES ('A101', '김유신', '010-1234-1111', 25);
insert into user1 values ('A101', '김춘추', '010-1234-2222', 23);
insert into user1 values ('A103', '장보고', '010-1234-3333', 32);
insert into user1 (user_id, name, age) values ('A104', '강감찬', 45);
insert into user1 (user_id, name, hp) 
                    values ('A105', '이순신', '010-1234-5555');

// 실습하기 1-6
select * from user1;
SELECT * FROM USER1 WHERE USER_ID = 'A101';
SELECT * FROM USER1 WHERE NAME = '김춘추';
SELECT * FROM USER1 WHERE AGE > 30;

select user_id, name, age from user1;

// 실습하기 1-7
UPDATE USER1 SET 
                HP = '010-1234-1001',
                AGE = 27
             WHERE 
                USER_ID = 'A101';

// 실습하기 1-8
DELETE FROM USER1 WHERE USER_ID = 'A101';
DELETE FROM USER1 WHERE USER_ID = 'A102' AND AGE = 25;
DELETE FROM USER1 WHERE AGE >= 30;

-----------------------------------------------
// 2.제약 조건
-----------------------------------------------

-- 실습하기 2-1
CREATE TABLE USER2 (
    USER_ID VARCHAR2(20) PRIMARY KEY,
    NAME VARCHAR2(20),
    HP CHAR(13),
    AGE NUMBER(2)
);

-- primary key(기본키) 컬럼은 중복 안됨
INSERT INTO USER2 VALUES ('A101', '김유신', '010-1234-1111', 23);
insert into user2 values ('A102', '김춘추', '010-1234-2222', 21);

// 실습하기 2-2
create table user3 (
    user_id     varchar2(20) primary key,
    name        varchar2(20),
    hp          char(13) UNIQUE,
    age         number(3)
);

insert into user3 values ('a101', '김유신', '010-1234-1001', 23);
insert into user3 values ('a102', '김춘추', '010-1234-1002', 21);

// 실습하기 2-3
CREATE TABLE PARENT(
    PID     VARCHAR2(20) PRIMARY KEY,
    NAME    VARCHAR2(20),
    HP      CHAR(13) UNIQUE
);
    
CREATE TABLE CHILD(
    CID     VARCHAR2(20) PRIMARY KEY,
    NAME    VARCHAR2(20),
    HP   CHAR(13) UNIQUE
    PARENT VARCHAR(20),
    FOREIGN KEY (PARENT) REFERENCES PARENT (PID)
);
    
INSERT INTO PARENT VALUES ('P101', '김서현', '010-1234-1001');
INSERT INTO PARENT VALUES ('P102', '이성계', '010-1234-1002');
INSERT INTO PARENT VALUES ('P103', '신사임당', '010-1234-1003');

INSERT INTO CHILD VALUES ('C101', '김유신', '010-1234-2001', 'P101');
INSERT INTO CHILD VALUES ('C102', '이방우', '010-1234-2002', 'P102');
INSERT INTO CHILD VALUES ('C103', '이방원', '010-1234-2003', 'P102');
INSERT INTO CHILD VALUES ('C104', '이이', '010-1234-2004', 'P103');

// 실습하기 2-4
CREATE TABLE USER4 (
    NAME    VARCHAR2(20) NOT NULL,
    GENDER  CHAR(1) NOT NULL,
    AGE     INT DEFAULT 1,
    ADDR    VARCHAR2(255)    
);

INSERT INTO USER4 VALUES ('김유신', 'M', 23, '김해시');
INSERT INTO USER4 VALUES ('김춘추', 'M', 21, '경주시');
INSERT INTO USER4 (NAME, GENDER, ADDR) VALUES ('신사임당', 'F', '강릉시');
INSERT INTO USER4 (NAME, GENDER) VALUES ('이순신', 'M');
INSERT INTO USER4 (NAME, AGE) VALUES ('정약용', 33);

// USER5
CREATE TABLE USER5 (
    NAME    VARCHAR2(20) NOT NULL,
    GENDER  CHAR(1) NOT NULL CHECK(GENDER IN('M', 'F')),
    AGE     INT DEFAULT 1 CHECK(AGE > 0 AND AGE < 100),
    ADDR    VARCHAR2(255)
);

INSERT INTO USER5 VALUES ('김유신', 'M', 23, '김해시');
INSERT INTO USER5 VALUES ('김춘추', 'M', 21, '경주시');
INSERT INTO USER5 (NAME, GENDER, ADDR) VALUES ('신사임당', 'F', '강릉시');
INSERT INTO USER5 (NAME, GENDER) VALUES ('이순신', 'M');
INSERT INTO USER5 (NAME, AGE) VALUES ('정약용', 33);

// USER7
CREATE TABLE USER7 (
    ID    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NAME  VARCHAR2(20),
    AGE   NUMBER,
    EMATL VARCHAR2(100)
);

INSERT INTO USER7 (NAME, AGE, EMATL) VALUES ('김유신', 25, 'kim@gmail.com');
INSERT INTO USER7 (NAME, AGE, EMATL) VALUES ('장보고', 35, 'jan@gmail.com');
INSERT INTO USER7 (NAME, AGE, EMATL) VALUES ('이순신', 45, 'lee@gmail.com');






