create table files (
    no number generated by default as identity primary key,
    title varchar2(100) not null,
    name  varchar2(100)not null,
    oName varchar2(200)not null,
    Sname varchar2(200)not null,
    rdate date not null
);