/*
    날짜 : 2025/07/17
    이름 : 이준우
    내용 : 5장 데이터베이스 객체

*/

-- 워크북 p13
-- 실습하기 3-1
SELECT * FROM DICTIONARY;

SELECT TABLE_NAME FROM USER_TABLES;
SELECT OWNER, TABLE_NAME FROM ALL_TABLES;
SELECT * FROM DBA_TABLES;