CREATE TABLE USER1 (
    USER_ID VARCHAR2(20),
    NAME VARCHAR2(20),
    HP CHAR(13),
    AGE NUMBER
);

INSERT INTO USER1 VALUES ('A101', '김유신', '010-1234-1111', 25);
insert into user1 values ('A101', '김춘추', '010-1234-2222', 23);
insert into user1 values ('A103', '장보고', '010-1234-3333', 32);
insert into user1 (user_id, name, age) values ('A104', '강감찬', 45);
insert into user1 (user_id, name, hp) values ('A105', '이순신', '010-1234-5555');


CREATE TABLE USER2 (
    USER_ID VARCHAR2(20) PRIMARY KEY,
    NAME VARCHAR2(20),
    HP CHAR(13),
    AGE NUMBER(2)
);

INSERT INTO USER2 VALUES ('A101', '김유신', '010-1234-1111', 23);
insert into user2 values ('A102', '김춘추', '010-1234-2222', 21);

create table user3 (
    user_id     varchar2(20) primary key,
    name        varchar2(20),
    hp          char(13) UNIQUE,
    age         number(3)
);

insert into user3 values ('a101', '김유신', '010-1234-1001', 23);
insert into user3 values ('a102', '김춘추', '010-1234-1002', 21);


create table customer (
    CID         VARCHAR2(20) PRIMARY KEY,
    NAME        VARCHAR2(20) NOT NULL,
    HP          CHAR(13) UNIQUE,
    ADDRESS     VARCHAR2(200),
    RDATE       DATE NOT NULL
);

insert into customer values ('c101', '김유신', '010-1234-1001', '김해시 봉황동', '2022-01-01');
insert into customer values ('c102', '김춘추', '010-1234-1002', '경주시 보문동', '2022-01-02');
insert into customer values ('c103', '장보고', '010-1234-1003', '완도군 청산면', '2022-01-03');
insert into customer values ('c104', '강감찬', '010-1234-1004', '서울시 마포구', '2022-01-04');
insert into customer values ('c105', '이성계', NULL, NULL, '2022-01-05');
insert into customer values ('c106', '정철', '010-1234-1006', '경기도 용인시', '2022-01-06');
insert into customer values ('c107', '허준', NULL, NULL, '2022-01-07');
insert into customer values ('c108', '이순신', '010-1234-1008', '서울시 영등포구', '2022-01-08');
insert into customer values ('c109', '송상현', '010-1234-1009', '부산시 동래구', '2022-01-09');
insert into customer values ('c110', '정약용', '010-1234-1010', '경기도 광주시', '2022-01-10');

drop table user4;
create table user4(
    name	varchar(10) primary key,
    gender	char(1), 
    age		int default 1,
    addr	varchar(100)
);

insert into user4 values('김유신', 'M', '23', '김해시');
insert into user4 values('뭐여', 'F', '21', '강릉시');

create table user5(
	name	varchar(15)primary key,
	gender	char(1) check (gender in ('M', 'F')),
    age		int default 1 check(age > 0 and age < 100),
    addr	varchar(20)
);

insert into user5(name, gender, age, addr) values ('김유신', 'M', 23, '김해시');
insert into user5(name, gender, age, addr) values ('신사임당', 'F', 21, '강릉시');
insert into user5(name, gender, age, addr) values ('허난설현', 'M', 21, '충주시');

CREATE TABLE USER7 (
ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
NAME VARCHAR2(20),
AGE NUMBER,
EMAIL VARCHAR2(100)
)

INSERT INTO USER7 (NAME, AGE, EMAIL) VALUES ('김유신', 25, 'kim@gmail.com');
INSERT INTO USER7 (NAME, AGE, EMAIL) VALUES ('장보고', 35, 'jang@gmail.com');
INSERT INTO USER7 (NAME, AGE, EMAIL) VALUES ('이순신', 45, 'lee@gmail.com');

CREATE TABLE USER6 (
    NAME VARCHAR2(20) PRIMARY KEY,
    GENDER CHAR(1),
    AGE NUMBER,
    ADDR VARCHAR2(255)
);

INSERT INTO USER6 VALUES ('김유신', 'M', 25, '김해시');
INSERT INTO USER6 VALUES ('김춘추', 'M', 23, '경주시');
INSERT INTO USER6 VALUES ('신사임당', 'F', 27, '강릉시');