CREATE TABLE notice (
  notice_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category    VARCHAR2(30)   NOT NULL,
  title       VARCHAR2(200)  NOT NULL,
  content     CLOB           NOT NULL,
  status      VARCHAR2(20)   DEFAULT 'VISIBLE' NOT NULL,
  created_at  TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at  TIMESTAMP
);

INSERT INTO notice (category, title, content, created_at)
VALUES ('안내', '해외결제사 정기점검주의',
        '해외결제사 정기점검으로 인한 서비스 일시 중단 안내드립니다.',
        TO_TIMESTAMP('2022-10-31 00:00:00','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO notice (category, title, content, created_at)
VALUES ('고객서비스', '고객센터 운영시간 변경',
        '고객센터 운영시간이 변경되었습니다. 자세한 내용은 고객센터로 문의 바랍니다.',
        TO_TIMESTAMP('2022-11-01 00:00:00','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO notice (category, title, content, created_at)
VALUES ('안전거래', '안전거래 정책 안내',
        '안전거래 정책에 대한 안내입니다.',
        TO_TIMESTAMP('2022-11-02 00:00:00','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO notice (category, title, content, created_at)
VALUES ('위해상품', '리콜 공지사항',
        '위해상품 리콜 공지사항입니다.',
        TO_TIMESTAMP('2022-11-03 00:00:00','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO notice (category, title, content, created_at)
VALUES ('이벤트당첨', '이벤트 당첨자 발표',
        '이벤트 당첨자 명단이 발표되었습니다.',
        TO_TIMESTAMP('2022-11-04 00:00:00','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO notice (category, title, content, created_at)
VALUES ('안내', '시스템 점검 안내',
        '서비스 안정화를 위한 시스템 점검 안내입니다.',
        TO_TIMESTAMP('2022-11-05 00:00:00','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO notice (category, title, content, created_at)
VALUES ('고객서비스', '서비스 개선 안내',
        '일부 기능 개선 안내드립니다.',
        TO_TIMESTAMP('2022-11-06 00:00:00','YYYY-MM-DD HH24:MI:SS'));

CREATE TABLE faq (
  faq_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category    VARCHAR2(50)   NOT NULL,
  question    VARCHAR2(255)  NOT NULL,
  answer      CLOB           NOT NULL,
  status      VARCHAR2(20)   DEFAULT 'VISIBLE' NOT NULL,
  created_at  TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at  TIMESTAMP
);

INSERT INTO faq (category, question, answer, status, created_at)
VALUES ('회원', '개인회원과 법인회원 차이가 있나요?',
        '개인회원은 일반 사용자이며, 법인회원은 사업자 등록이 필요합니다.',
        'VISIBLE', TO_TIMESTAMP('2025-02-01 09:00:00','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO faq (category, question, answer, status, created_at)
VALUES ('회원', '회원 탈퇴 후 재가입이 가능한가요?',
        '탈퇴 후 30일간은 재가입이 제한됩니다.',
        'VISIBLE', TO_TIMESTAMP('2025-02-02 09:00:00','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO faq (category, question, answer, status, created_at)
VALUES ('회원', '비밀번호를 잊었어요.',
        '로그인 페이지의 비밀번호 찾기를 이용해 주세요.',
        'VISIBLE', TO_TIMESTAMP('2025-02-03 09:00:00','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO faq (category, question, answer, status, created_at)
VALUES ('쿠폰/이벤트', '쿠폰은 어디서 확인하나요?',
        '마이페이지 > 쿠폰함에서 확인 가능합니다.',
        'VISIBLE', TO_TIMESTAMP('2025-02-04 09:00:00','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO faq (category, question, answer, status, created_at)
VALUES ('쿠폰/이벤트', '이벤트 당첨 결과는 어디서 보나요?',
        '공지사항 또는 개별 문자로 안내드립니다.',
        'VISIBLE', TO_TIMESTAMP('2025-02-05 09:00:00','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO faq (category, question, answer, status, created_at)
VALUES ('주문/결제', '주문 내역은 어디서 확인하나요?',
        '마이페이지 > 주문내역에서 확인할 수 있습니다.',
        'VISIBLE', TO_TIMESTAMP('2025-02-06 09:00:00','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO faq (category, question, answer, status, created_at)
VALUES ('주문/결제', '결제수단은 어떤 것이 있나요?',
        '신용카드, 계좌이체, 휴대폰 결제 등이 있습니다.',
        'VISIBLE', TO_TIMESTAMP('2025-02-07 09:00:00','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO faq (category, question, answer, status, created_at)
VALUES ('배송', '배송 조회는 어떻게 하나요?',
        '마이페이지 > 주문내역 > 배송조회에서 확인 가능합니다.',
        'VISIBLE', TO_TIMESTAMP('2025-02-08 09:00:00','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO faq (category, question, answer, status, created_at)
VALUES ('배송', '배송비는 얼마인가요?',
        '3만원 이상 구매 시 무료배송입니다.',
        'VISIBLE', TO_TIMESTAMP('2025-02-09 09:00:00','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO faq (category, question, answer, status, created_at)
VALUES ('취소/반품/교환', '주문 취소는 어떻게 하나요?',
        '상품 준비 중 상태일 때만 직접 취소 가능합니다.',
        'VISIBLE', TO_TIMESTAMP('2025-02-10 09:00:00','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO faq (category, question, answer, status, created_at)
VALUES ('취소/반품/교환', '교환은 어떻게 하나요?',
        '고객센터를 통해 신청해 주세요.',
        'VISIBLE', TO_TIMESTAMP('2025-02-11 09:00:00','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO faq (category, question, answer, status, created_at)
VALUES ('여행/숙박/항공', '예약 후 변경 가능한가요?',
        '상품에 따라 변경 가능 여부가 다르니 상세정보를 확인하세요.',
        'VISIBLE', TO_TIMESTAMP('2025-02-12 09:00:00','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO faq (category, question, answer, status, created_at)
VALUES ('여행/숙박/항공', '여권 정보 입력은 필수인가요?',
        '항공권 예약 시 필수입니다.',
        'VISIBLE', TO_TIMESTAMP('2025-02-13 09:00:00','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO faq (category, question, answer, status, created_at)
VALUES ('안전거래', '안전거래란 무엇인가요?',
        '구매자와 판매자 간 안전한 결제를 보장하는 서비스입니다.',
        'VISIBLE', TO_TIMESTAMP('2025-02-14 09:00:00','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO faq (category, question, answer, status, created_at)
VALUES ('안전거래', '에스크로 서비스는 어떻게 이용하나요?',
        '자동으로 적용되며 별도 설정은 필요 없습니다.',
        'VISIBLE', TO_TIMESTAMP('2025-02-15 09:00:00','YYYY-MM-DD HH24:MI:SS'));

drop table qna;
CREATE TABLE qna (
  qna_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id         NUMBER,
  category        VARCHAR2(50)  NOT NULL,
  type_label      VARCHAR2(50)  NOT NULL,
  title           VARCHAR2(200) NOT NULL,
  content         CLOB           NOT NULL,
  status          VARCHAR2(20)  DEFAULT '검토 중' NOT NULL,
  writer          VARCHAR2(100) NOT NULL,
  created_at      TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at      TIMESTAMP,
  answer_content  CLOB,
  answer_admin_id NUMBER,
  answered_at     TIMESTAMP
);

INSERT INTO qna (user_id, category, type_label, title, content, status, writer, created_at)
VALUES (201, '회원', '가입', '가입 문의내용', '회원가입하고 싶어요. 어떻게 해야 하나요?', '검토 중', 'chk**',
        TO_TIMESTAMP('2022-10-31 09:00:00','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO qna (user_id, category, type_label, title, content, status, writer, created_at)
VALUES (201, '회원', '탈퇴', '탈퇴 문의내용', '탈퇴 절차가 궁금합니다.', '검토 중', 'chk**',
        TO_TIMESTAMP('2022-10-31 10:00:00','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO qna (user_id, category, type_label, title, content, status, writer, created_at, answer_content, answered_at, answer_admin_id)
VALUES (201, '회원', '회원정보', '회원정보 문의내용', '회원 정보 수정은 어디서 하나요?', '답변완료', 'chk**',
        TO_TIMESTAMP('2022-10-31 11:00:00','YYYY-MM-DD HH24:MI:SS'),
        '마이페이지 > 회원정보에서 수정 가능합니다.', TO_TIMESTAMP('2022-10-31 15:00:00','YYYY-MM-DD HH24:MI:SS'), 9001);
INSERT INTO qna (user_id, category, type_label, title, content, status, writer, created_at)
VALUES (202, '쿠폰/이벤트', '쿠폰', '쿠폰 사용 문의', '쿠폰 적용이 안 됩니다.', '검토 중', 'chk**',
        TO_TIMESTAMP('2022-11-01 09:00:00','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO qna (user_id, category, type_label, title, content, status, writer, created_at, answer_content, answered_at, answer_admin_id)
VALUES (202, '쿠폰/이벤트', '이벤트', '이벤트 응모 문의', '응모 방법을 알려주세요.', '답변완료', 'chk**',
        TO_TIMESTAMP('2022-11-02 09:00:00','YYYY-MM-DD HH24:MI:SS'),
        '이벤트 상세 페이지 하단 응모 버튼을 이용해 주세요.', TO_TIMESTAMP('2022-11-02 14:00:00','YYYY-MM-DD HH24:MI:SS'), 9001);
INSERT INTO qna (user_id, category, type_label, title, content, status, writer, created_at)
VALUES (203, '주문/결제', '결제', '결제 오류 발생', '카드 결제 오류 코드가 떠요.', '검토 중', 'chk**',
        TO_TIMESTAMP('2022-11-03 09:00:00','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO qna (user_id, category, type_label, title, content, status, writer, created_at, answer_content, answered_at, answer_admin_id)
VALUES (203, '주문/결제', '주문', '주문 내역 문의', '예전 주문 내역이 보이지 않습니다.', '답변완료', 'chk**',
        TO_TIMESTAMP('2022-11-04 09:00:00','YYYY-MM-DD HH24:MI:SS'),
        '기간 필터를 확장하시거나 비회원 주문의 경우 주문번호+연락처 확인이 필요합니다.', TO_TIMESTAMP('2022-11-04 16:30:00','YYYY-MM-DD HH24:MI:SS'), 9002);
INSERT INTO qna (user_id, category, type_label, title, content, status, writer, created_at)
VALUES (204, '배송', '배송', '배송 지연 문의', '예상일보다 늦어지고 있어요.', '검토 중', 'chk**',
        TO_TIMESTAMP('2022-11-05 09:00:00','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO qna (user_id, category, type_label, title, content, status, writer, created_at)
VALUES (205, '취소/반품/교환', '반품', '반품 신청 방법', '반품 절차를 알려주세요.', '검토 중', 'chk**',
        TO_TIMESTAMP('2022-11-06 09:00:00','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO qna (user_id, category, type_label, title, content, status, writer, created_at, answer_content, answered_at, answer_admin_id)
VALUES (206, '여행/숙박/항공', '숙박', '숙박 예약 취소', '숙박 예약을 취소하고 싶어요.', '답변완료', 'chk**',
        TO_TIMESTAMP('2022-11-07 09:00:00','YYYY-MM-DD HH24:MI:SS'),
        '숙박 예약은 체크인 3일 전까지 무료 취소 가능합니다. 상품별 정책을 확인해 주세요.', TO_TIMESTAMP('2022-11-07 13:20:00','YYYY-MM-DD HH24:MI:SS'), 9003);
INSERT INTO qna (user_id, category, type_label, title, content, status, writer, created_at)
VALUES (207, '안전거래', '보안', '보안 관련 문의', '개인정보 보호가 걱정됩니다.', '검토 중', 'chk**',
        TO_TIMESTAMP('2022-11-08 09:00:00','YYYY-MM-DD HH24:MI:SS'));

